EmployeeManagement.ConsumeAPI/Models/Employee.cs
using System.Reflection;

namespace EmployeeManagement.ConsumeAPI.Models
{
    public class Employee
    {
        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public DateTime DateOfBrith { get; set; }
        public Gender Gender { get; set; }
        public int DepartmentId { get; set; }
        public string PhotoPath { get; set; }
      
    }


    public enum Gender
    {
        Male,
        Female,
        Other
    }

}

EmployeeManagement.ConsumeAPI/Controllers/ConsumeByjQueryController.cs
using EmployeeManagement.ConsumeAPI.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace EmployeeManagement.ConsumeAPI.Controllers
{
    public class ConsumeByjQueryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AllEmployees()
        {
            return View();
        }

        public ViewResult AddEmployeejQ() => View();

        public ViewResult UpdateEmployeejQ(int id) => View();

        public ViewResult DeleteEmployeejQ(int id) => View();

        public ViewResult GetEmployeeDetailsJQ(int id) => View();

        public ViewResult AddFilejQ() => View();


    }
}

EmployeeManagement.ConsumeAPI/Controllers/HomeController.cs
using EmployeeManagement.ConsumeAPI.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace EmployeeManagement.ConsumeAPI.Controllers
{
    public class HomeController : Controller
    {
        public async Task<IActionResult> Index()
        {

            List<Employee> employeeList = new List<Employee>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:44354/api/Employees"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    employeeList = JsonConvert.DeserializeObject<List<Employee>>(apiResponse);
                }
            }
            return View(employeeList);
        }


        public async Task<IActionResult> EmployeeDetails(int id)
        {

            Employee employee = new Employee();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:44354/api/Employees/" + id))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        employee = JsonConvert.DeserializeObject<Employee>(apiResponse);
                    }
                    else
                        ViewBag.StatusCode = response.StatusCode;
                }
            }
            return View(employee);
        }

        public ViewResult AddEmployee() => View();


        [HttpPost]
        public async Task<IActionResult> AddEmployee(Employee employee)
        {
            Employee receivedEmployee = new Employee();

            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(employee), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync("https://localhost:44354/api/Employees", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    receivedEmployee = JsonConvert.DeserializeObject<Employee>(apiResponse);
                }
            }
            return View(receivedEmployee);
        }


        public async Task<IActionResult> UpdateEmployee(int id)
        {
            Employee employee = new Employee();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:44354/api/Employees/" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    employee = JsonConvert.DeserializeObject<Employee>(apiResponse);
                }
            }
            return View(employee);
        }

        //[HttpPost]
        //public async Task<IActionResult> UpdateEmployee(Employee employee)
        //{
        //    Employee receivedEmployee = new Employee();

        //    using (var httpClient = new HttpClient())
        //    {
        //        httpClient.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

        //        var content = new MultipartFormDataContent();
        //        content.Add(new StringContent(employee.EmployeeId.ToString()), "EmployeeId");
        //        content.Add(new StringContent(employee.FirstName), "FirstName");
        //        content.Add(new StringContent(employee.LastName), "LastName");
        //        content.Add(new StringContent(employee.Email), "Email");

        //        content.Add(new StringContent(employee.DateOfBrith.ToString()), "DateOfBrith");
        //        content.Add(new StringContent(employee.Gender.ToString()), "Gender");
        //        content.Add(new StringContent(employee.DepartmentId.ToString()), "DepartmentId");
        //        content.Add(new StringContent(employee.PhotoPath), "PhotoPath");


        //        using (var response = await httpClient.PutAsync("https://localhost:7166/api/Employees/" + employee.EmployeeId.ToString(), content))
        //        {
        //            if (response.StatusCode == System.Net.HttpStatusCode.NoContent)
        //            {
        //                ViewBag.Result = "Success";

        //            }
        //            else
        //            {
        //                ViewBag.Result = "Failed";
        //                ViewBag.StatusCode = response.StatusCode;
        //            }
        //        }
        //    }

        //    return View();
        //}


        [HttpPost]
        public async Task<IActionResult> UpdateEmployee(Employee employee)
        {

            Employee receivedEmployee = new Employee();

            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(employee), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PutAsync("https://localhost:44354/api/Employees/" + employee.EmployeeId.ToString(), content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.Result = "Success";
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        receivedEmployee = JsonConvert.DeserializeObject<Employee>(apiResponse);
                    }
                    else
                    {
                        ViewBag.Result = "Failed";
                        ViewBag.StatusCode = response.StatusCode;
                    }
                }
            }
            return View(receivedEmployee);

        }


        public async Task<IActionResult> DeleteEmployee(int id)
        {
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.DeleteAsync("https://localhost:44354/api/Employees/" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }

            return RedirectToAction("Index");
        }


    }
}

EmployeeManagement.ConsumeAPI/Views/ConsumeByjQuery/AddEmployeejQ.cshtml
@model Employee
@{
    Layout = "_Layout"; ViewBag.Title = "Add a Employee";
}


<h2>Enter Employee Info:</h2>

<br />
<div class="col-md-4">

    @*<form asp-action="AddEmployee" method="post">*@

        <div class="form-group">
            <label for="FirstName">First Name:</label>
            <input class="form-control" id="FirstName" />
        </div>
        <div class="form-group">
            <label for="LastName">Last Name:</label>
            <input class="form-control" id="LastName" />
        </div>
        <div class="form-group">
            <label for="Email">Email:</label>
            <input class="form-control" id="Email" />
        </div>

        <div class="form-group">
            <label for="DateOfBrith">Date of Birth:</label>
            <input class="form-control" id="DateOfBrith" />
        </div>
        <div class="form-group">
            <label for="Gender">Gender:</label>
            <input class="form-control" id="Gender" />
        </div>
        <div class="form-group">
            <label for="DepartmentId">Department:</label>
            <input class="form-control" id="DepartmentId" />
        </div>
        <div class="form-group">
            <label for="PhotoPath">Photo Path:</label>
            <input class="form-control" id="PhotoPath" />
        </div>
        <br />
        <div class="form-group row">
            <div class="col-md-6">
                <button type="submit" class="btn btn-sm btn-primary" id="AddButton">Add</button>
            </div>
            <div class="col-md-6" style="text-align:right">
                <h2><a asp-action="AllEmployees" asp-controller="ConsumeByjQuery" class="btn btn-sm btn-secondary">Employee List</a></h2>
            </div>
        </div>
    @*</form>*@

</div>


<div style="display:none" id="resultDiv">
    <h2>Added Employee:</h2>

    <br />
    <div class="row col-md-4">
        <div class="col-md-6">Employee Id:</div> <div class="col-md-6" id="idDiv"></div>
        <div class="col-md-6">First Name:</div> <div class="col-md-6" id="firstNameDiv"></div>
        <div class="col-md-6">Last Name:</div> <div class="col-md-6" id="lastNameDiv"></div>
        <div class="col-md-6">Email:</div> <div class="col-md-6" id="emailDiv"></div>
        <div class="col-md-6">Date of Birth:</div> <div class="col-md-6" id="dobDiv"></div>
        <div class="col-md-6">Gender:</div> <div class="col-md-6" id="genderDiv"></div>
        <div class="col-md-6">Department Id:</div> <div class="col-md-6" id="deptIdDiv"></div>
        <div class="col-md-6">Photo Path:</div> <div class="col-md-6" id="photoPathDiv"></div>

    </div>

</div>

<script type="text/javascript">

    $("#AddButton").on('click', function (e) {
        
       // alert("About to call...");
        
        $.ajax({
            url: "https://localhost:44354/api/employees",
            type: "post",
            contentType: "application/json",
            data: JSON.stringify({
                FirstName: $("#FirstName").val(),
                LastName: $("#LastName").val(),
                Email: $("#Email").val(),
                DateOfBrith: $("#DateOfBrith").val(),
                Gender: $("#Gender").val(),
                DepartmentId: $("#DepartmentId").val(),
                PhotoPath: $("#PhotoPath").val()
            }),
            success: function (result, status, xhr) {
                
                //alert("I am in success...");
                
                //var str = "<tr><td>" + result["id"] + "</td><td>" + result["name"] + "</td><td>" + result["startLocation"] + "</td><td>" + result[
                //    $("table tbody").append(str);

                $("#idDiv").append(result.employeeId)
                $("#firstNameDiv").append(result.firstName)
                $("#lastNameDiv").append(result.lastName)
                $("#emailDiv").append(result.email)
                $("#dobDiv").append(result.dateOfBrith)
                $("#genderDiv").append(result.gender)
                $("#deptIdDiv").append(result.departmentId)
                $("#photoPathDiv").append(result.photoPath)

                $("#resultDiv").show();
            },
            error: function (xhr, status, error) {

                //alert("I am in error...");
                console.log(xhr)
            }
        });
    });

</script>

EmployeeManagement.ConsumeAPI/Views/ConsumeByjQuery/AddFileJQ.cshtml
@{
    Layout = "_Layout"; ViewBag.Title = "Employee Details";
}


<br />

<div class="container-fluid">
    <h2>Add File</h2>
    
    <input type="file" id="File" />
    <div class="text-center panel-body">
        <button id="AddButton" type="submit" class="btn btn-sm btn-primary">Add</button>
    </div>

    <div id="fileDiv" style="display:none">
        <h2>Uploaded File</h2>
        <img id="fileImg" />
    </div>
</div>


<script type="text/javascript">
    $(document).ready(function () {
        $("#AddButton").click(function (e) {
            data = new FormData();
            data.append("file", $("#File")[0].files[0]);

            $.ajax({
                url: "https://localhost:44354/api/employees/UploadFile",
                type: "post",
                data: data,
                processData: false,
                contentType: false,
                success: function (result, status, xhr) {
                    $("#fileImg").attr("src", result);
                    $("#fileDiv").show();
                },
                error: function (xhr, status, error) {
                    console.log(xhr)
                }
            });
        });
    });
</script>

EmployeeManagement.ConsumeAPI/Views/ConsumeByjQuery/AllEmployees.cshtml
@{
    Layout = "_Layout"; ViewBag.Title = "All Employees";
}


<table class="table table-sm table-striped table-bordered m-2" id="table1">
    <thead>
        <tr>
            <th style="text-align:center">Employee ID</th>
            <th style="text-align:center">First Name</th>
            <th style="text-align:center">Last Name</th>
            <th style="text-align:center">Email</th>
            <th style="text-align:center">Gender</th>
              <th style="text-align:center">Actions</th>
@*            <th style="text-align:center">Delete</th>
            <th style="text-align:center">Details</th>*@
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

<br />

<a asp-action="AddEmployeejQ" class="btn btn-sm btn-primary">Add Employee(jQ)</a>

<a asp-action="AddFilejQ" class="btn btn-sm btn-primary">Test File Uploading(JQ)</a>

<script type="text/javascript">

    $(document).ready(function () {

        ShowAllEmployees();

        $("table").on("click", "img.delete", function () {
            var reservationId = $(this).parents("tr").find("td:nth-child(1)").text();

            $.ajax({
                url: "https://localhost:44324/api/Reservation/" + reservationId,
                type: "delete",
                contentType: "application/json",
                success: function (result, status, xhr) {
                    ShowAllReservation();
                },
                error: function (xhr, status, error) {
                    console.log(xhr)
                }
            });
        });

    });

    function ShowAllEmployees() {
        $("table tbody").html("");
        $.ajax({
            url: "https://localhost:44354/api/employees",
            type: 'GET',
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (result, status, xhr) {
                //alert("I am in success...");
                $.each(result, function (index, value) {
                    //alert("Employee Id: " + value.employeeId);
                    $("tbody").append($("<tr>"));
                    appendElement = $("tbody tr").last(); 
                    appendElement.append($("<td style=\"vertical-align: middle; text-align: center;\">").html(value["employeeId"]));
                    appendElement.append($("<td style=\"vertical-align: middle; text-align: center;\">").html(value["firstName"]));
                    appendElement.append($("<td style=\"vertical-align: middle; text-align: center;\">").html(value["lastName"]));
                    appendElement.append($("<td style=\"vertical-align: middle; text-align: center;\">").html(value["email"]));
                    appendElement.append($("<td style=\"vertical-align: middle; text-align: center;\">").html(value["gender"]));
                    //appendElement.append($("<td>").html("Click here"));

                    //appendElement.append($("<td>").html("<a href=\"UpdateEmployeejQ/" + value["employeeId"] + "\"><img src=\"images/updateImage.jpg\" /></a>"));
                    //appendElement.append($("<td>").html("<a href=\"ConsumeByjQuery/UpdateEmployeejQ/" + value["employeeId"] + "\">Update</a>" + "<br/><a href=\"ConsumeByjQuery/DeleteEmployeejQ/" + value["employeeId"] + "\">Delete</a>" + "<br/><a href=\"ConsumeByjQuery/GetEmployeejQDetails/" + value["employeeId"] + "\">Details</a>"));

                    appendElement.append($("<td>").html("<a href=\"ConsumeByjQuery/UpdateEmployeejQ?id=" + value["employeeId"] + "\">Update</a>" + "<br/><a href=\"javascript:javascript:void(0)\" onClick=\"javascript:DeleteFunction(" + value["employeeId"] + ")\">Delete</a>" + "<br/><a href=\"ConsumeByjQuery/GetEmployeeDetailsJQ?id=" + value["employeeId"] + "\">Details</a>"));

                    
                    
                    //appendElement.append($("<td>").html("<a href=\"DeleteEmployeejQ/" + value["employeeId"] + "\">Delete</a>"));
                    //appendElement.append($("<td>").html("<a href=\"GetEmployeejQDetails/" + value["employeeId"] + "\">Details</a>"));

                    //appendElement.append($("<td>").html("<img class=\"delete\" src=\"icon/close.png\" />"));

                    //var tableString = "";
                    //$.each(result, function (index, value) {
                    //    tableString += "<tr><td>" + value.EmployeeId + "</td><td>" + value.FirstName + "</td><td>" + value.LastName + "</td><td>" + value.Email + "</td><td>" + value.Gender + "</td></tr>";
                    //});
                    //$("#table1").append(tableString);
                
                
                
                });
            },
            error: function (xhr, status, error) {
                alert("I am in error...");
                var acc = []
                $.each(xhr, function (index, value) {
                    acc.push(index + ': ' + value);
                });
                alert(JSON.stringify(acc));
            }
        });
    }

    function DeleteFunction(employeeId)
    {
        //alert("I am in DeleteFunction...and employeeId is: " + employeeId);
        $.ajax({
            url: "https://localhost:44354/api/employees/" + employeeId,
            type: "delete",
            contentType: "application/json",
            success: function (result, status, xhr) {
               // alert("I am in success...");
                ShowAllEmployees();
            },
            error: function (xhr, status, error) {
               // alert("I am in error...");
                console.log(xhr)
            }
        });

    }


</script>

EmployeeManagement.ConsumeAPI/Views/ConsumeByjQuery/DeleteEmployeejQ.cshtml
<h1>Delete is coming soon...</h1>

EmployeeManagement.ConsumeAPI/Views/ConsumeByjQuery/GetEmployeeDetailsJQ.cshtml
@{
    Layout = "_Layout"; ViewBag.Title = "Employee Details";
}

<div style="display:none" id="resultDiv">

    <br />

    <h6>Employee Details:</h6>

    <br />
    <div class="row col-md-4">
        <div class="col-md-6">Employee Id:</div> <div class="col-md-6" id="idDiv"></div>
        <div class="col-md-6">First Name:</div> <div class="col-md-6" id="firstNameDiv"></div>
        <div class="col-md-6">Last Name:</div> <div class="col-md-6" id="lastNameDiv"></div>
        <div class="col-md-6">Email:</div> <div class="col-md-6" id="emailDiv"></div>
        <div class="col-md-6">Date of Birth:</div> <div class="col-md-6" id="dobDiv"></div>
        <div class="col-md-6">Gender:</div> <div class="col-md-6" id="genderDiv"></div>
        <div class="col-md-6">Department Id:</div> <div class="col-md-6" id="deptIdDiv"></div>
        <div class="col-md-6">Photo Path:</div> <div class="col-md-6" id="photoPathDiv"></div>

    </div>

    <br />

    <div class="col-md-6" style="text-align:left">
        <h2><a asp-action="AllEmployees" asp-controller="ConsumeByjQuery" class="btn btn-sm btn-secondary">Got to Employee List</a></h2>
    </div>

</div>

<script type="text/javascript">

    $(document).ready(

        function () {
            alert("I am in document ready...");
            GetEmployee();

        }

    )

    function GetEmployee() {

        alert("I am in get employee...");
        let params = (new URL(document.location)).searchParams;
        let id = params.get("id");

        alert("The id is: " + id);

        $.ajax({
            url: "https://localhost:44354/api/employees/" + id,
            type: "get",
            contentType: "application/json",
            success: function (result, status, xhr) {
                alert("I am in success...");

                $("#idDiv").append(result.employeeId)
                $("#firstNameDiv").append(result.firstName)
                $("#lastNameDiv").append(result.lastName)
                $("#emailDiv").append(result.email)
                $("#dobDiv").append(result.dateOfBrith)
                $("#genderDiv").append(result.gender)
                $("#deptIdDiv").append(result.departmentId)
                $("#photoPathDiv").append(result.photoPath)

                $("#resultDiv").show();
            },
            error: function (xhr, status, error) {
                alert("I am in error...");
                console.log(xhr)
            }
        });
    }

</script>

EmployeeManagement.ConsumeAPI/Views/ConsumeByjQuery/UpdateEmployeejQ.cshtml
@{
    Layout = "_Layout"; ViewBag.Title = "Update Employee";
}



<div style="display:none" id="resultDiv">

    <h6>Employee was updated successfully as below:</h6>

    <br />
    <div class="row col-md-4">
        <div class="col-md-6">Employee Id:</div> <div class="col-md-6" id="idDiv"></div>
        <div class="col-md-6">First Name:</div> <div class="col-md-6" id="firstNameDiv"></div>
        <div class="col-md-6">Last Name:</div> <div class="col-md-6" id="lastNameDiv"></div>
        <div class="col-md-6">Email:</div> <div class="col-md-6" id="emailDiv"></div>
        <div class="col-md-6">Date of Birth:</div> <div class="col-md-6" id="dobDiv"></div>
        <div class="col-md-6">Gender:</div> <div class="col-md-6" id="genderDiv"></div>
        <div class="col-md-6">Department Id:</div> <div class="col-md-6" id="deptIdDiv"></div>
        <div class="col-md-6">Photo Path:</div> <div class="col-md-6" id="photoPathDiv"></div>

    </div>

    <br />

    <div class="col-md-6" style="text-align:left">
        <h2><a asp-action="AllEmployees" asp-controller="ConsumeByjQuery" class="btn btn-sm btn-secondary">Got to Employee List</a></h2>
    </div>

</div>

<div id="updateFormDiv">
    <h2>Update Employee: </h2>
    <br />

    <div class="col-md-4">

        <div class="form-group">
            <label for="EmployeeId"></label>
            <input class="form-control" id="EmployeeId" hidden />
        </div>
        <div class="form-group">
            <label for="FirstName">First Name:</label>
            <input class="form-control" id="FirstName" />
        </div>
        <div class="form-group">
            <label for="LastName">Last Name:</label>
            <input class="form-control" id="LastName" />
        </div>
        <div class="form-group">
            <label for="Email">Email:</label>
            <input class="form-control" id="Email" />
        </div>

        <div class="form-group">
            <label for="DateOfBrith">Date of Birth:</label>
            <input class="form-control" id="DateOfBrith" />
        </div>
        <div class="form-group">
            <label for="Gender">Gender:</label>
            <input class="form-control" id="Gender" />
        </div>
        <div class="form-group">
            <label for="DepartmentId">Department:</label>
            <input class="form-control" id="DepartmentId" />
        </div>
        <div class="form-group">
            <label for="PhotoPath">Photo Path:</label>
            <input class="form-control" id="PhotoPath" />
        </div>
        <br />
        <div class="form-group row">
            <div class="col-md-6">
                <button type="submit" class="btn btn-sm btn-primary" id="UpdateButton">Update</button>
            </div>
            <div class="col-md-6" style="text-align:right">
                <h2><a asp-action="AllEmployees" asp-controller="ConsumeByjQuery" class="btn btn-sm btn-secondary">Employee List</a></h2>
            </div>
        </div>

    </div>
</div>


<script type="text/javascript">

    $(document).ready(

        function () {
            //alert("I am in document ready...");
            GetEmployee();

        }

    )

    function GetEmployee() {

        //alert("I am in get employee...");
        let params = (new URL(document.location)).searchParams;
        let id = params.get("id");

        //alert("The id is: " + id);

        $.ajax({
            url: "https://localhost:44354/api/employees/" + id,
            type: "get",
            contentType: "application/json",
            success: function (result, status, xhr) {
                //alert("I am in success...");

                $("#EmployeeId").val(result["employeeId"]);
                $("#FirstName").val(result["firstName"]);
                $("#LastName").val(result["lastName"]);
                $("#Email").val(result["email"]);
                $("#DateOfBrith").val(result["dateOfBrith"]);
                $("#Gender").val(result["gender"]);
                $("#DepartmentId").val(result["departmentId"]);
                $("#PhotoPath").val(result["photoPath"]);
            },
            error: function (xhr, status, error) {
                //alert("I am in error...");
                console.log(xhr)
            }
        });
    }

    $("#UpdateButton").on('click',

        function (e) {

            //let params = (new URL(document.location)).searchParams;
            //let id = params.get("id");

            // alert("I am in update button function...");

            //data = new FormData();
            //data.append("EmployeeId", $("#EmployeeId").val());
            //data.append("FirstName", $("#FirstName").val());
            //data.append("LastName", $("#LastName").val());
            //data.append("Email", $("#Email").val());

            //data.append("DateOfBrith", $("#DateOfBrith").val());
            //data.append("Gender", $("#Gender").val());
            //data.append("DepartmentId", $("#DepartmentId").val());
            //data.append("PhotoPath", $("#PhotoPath").val());

           // alert("Id is: " + $("#EmployeeId").val());
            //alert(data.values());


            //$.ajax({
            //    url: "https://localhost:44354/api/employees/" + $("#EmployeeId").val(),
            //    type: "put",
            //    data: data,
            //    //processData: false,
            //    //contentType: false,
            //    contentType: "application/json; charset=utf-8",
            //    dataType: "json",


            var rawData = {
                EmployeeId: $("#EmployeeId").val(),
                FirstName: $("#FirstName").val(),
                LastName: $("#LastName").val(),
                Email: $("#Email").val(),
                DateOfBrith: $("#DateOfBrith").val(),
                Gender: $("#Gender").val(),
                DepartmentId: $("#DepartmentId").val(),
                PhotoPath: $("#PhotoPath").val()
            }

            var jsonData = JSON.stringify(rawData);
            //alert("Json data: " + jsonData);

            $.ajax({
                url: "https://localhost:44354/api/employees/" + $("#EmployeeId").val(),
                type: "PUT",
                contentType: "application/json",
                data: jsonData,
                success: function (result, status, xhr) {
                   // alert("I am in success...");

                    //var str = "<tr><td>" + result["id"] + "</td><td>" + result["name"] + "</td><td>" + result["startLocation"] + "</td><td>" + result[
                    //    $("table tbody").append(str);
                    //$("#resultDiv").show();


                    $("#idDiv").append(result.employeeId)
                    $("#firstNameDiv").append(result.firstName)
                    $("#lastNameDiv").append(result.lastName)
                    $("#emailDiv").append(result.email)
                    $("#dobDiv").append(result.dateOfBrith)
                    $("#genderDiv").append(result.gender)
                    $("#deptIdDiv").append(result.departmentId)
                    $("#photoPathDiv").append(result.photoPath)

                    $("#resultDiv").show();
                    $("#updateFormDiv").hide();
                },
                error: function (xhr, status, error) {
                    alert("I am in error...");
                    console.log(xhr)
                }
            });
        }
    )



</script>

EmployeeManagement.ConsumeAPI/Views/Home/Index.cshtml
@model IEnumerable<Employee>
@{
    Layout = "_Layout"; ViewBag.Title = "All Employees";
}

<div class="row">

    <div class="col-md-4">
        <h2>All Employees:</h2>
    </div>
    <div class="col-md-8">
        <a asp-controller="ConsumeByjQuery" asp-action="AllEmployees" class="btn btn-sm btn-primary">Use jQuery</a>
    </div>

</div>


@*<a asp-action="GetEmployee" class="btn btn-sm btn-secondary">Get Employee</a>*@

<table class="table table-sm table-striped table-bordered m-2">
    <thead>
        <tr>
            <th style="text-align:center">Employee ID</th>
            <th style="text-align:center">First Name</th>
            <th style="text-align:center">Last Name</th>
            <th style="text-align:center">Email</th>
            <th style="text-align:center">Gender</th>
            <th style="text-align:center">Update</th>
            <th style="text-align:center">Delete</th>
            <th style="text-align:center">Details</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var r in Model)
        {
            <tr>
                <td style="text-align:center">@r.EmployeeId</td>
                <td style="text-align:center">@r.FirstName</td>
                <td style="text-align:center">@r.LastName</td>
                <td style="text-align:center">@r.Email</td>
                <td style="text-align:center">@r.Gender</td>
                <td style="text-align:center">
                    <a asp-action="UpdateEmployee" asp-route-id="@r.EmployeeId">
                        <i class="fa fa-hand-point-right"></i>
                        @*  <img src="/icon/edit.png" />*@
                    </a>
                </td>
                <td style="text-align:center">
                    <a asp-action="DeleteEmployee" asp-route-id="@r.EmployeeId">
                        <i class="fa fa-hand-point-right"></i>
                        @*  <img src="/icon/edit.png" />*@
                    </a>
                </td>
                <td style="text-align:center">
                    <a asp-action="EmployeeDetails" asp-route-id="@r.EmployeeId">
                        <i class="fa fa-hand-point-right"></i>
                        @*  <img src="/icon/edit.png" />*@
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

<br />


<a asp-action="AddEmployee" class="btn btn-sm btn-primary">Add Employee</a>